export const BADGE_TIERS = {
  1: {
    bg: "bg-tier-1",
    ring: "bg-orange-100",
    text: "text-orange-700",
    description: "text-orange-600/80",
    icon: "text-orange-600",
    glow: "",
    animate: false,
  },
  2: {
    bg: "bg-tier-2",
    ring: "bg-yellow-200",
    text: "text-yellow-800",
    description: "text-yellow-700/80",
    icon: "text-yellow-700",
    glow: "ring-2 ring-yellow-300",
    animate: false,
  },
  3: {
    bg: "bg-tier-3",
    ring: "bg-yellow-300",
    text: "text-amber-900",
    description: "text-amber-800/85",
    icon: "text-amber-700",
    glow: "ring-4 ring-yellow-400 shadow-yellow-300/50",
    animate: true,
  },
};

export const BADGES = {
  FIRST_PIXEL_ART: {
    id: "first_pixel_art",
    name: "First Creation",
    description: "Created your first Pixel Art",
    icon: "🎨",
    requirement: 1,
    type: "pixel_art_count",
    tier: 1,
  },
  PIXEL_ART_COLLECTOR_10: {
    id: "pixel_art_collector_10",
    name: "Pixel Art Collector",
    description: "Created 10 Pixel Arts",
    icon: "🖼️",
    requirement: 10,
    type: "pixel_art_count",
    tier: 2,
  },
  PIXEL_ART_MASTER_100: {
    id: "pixel_art_master_100",
    name: "Pixel Master",
    description: "Created 100 Pixel Arts",
    icon: "🏆",
    requirement: 100,
    type: "pixel_art_count",
    tier: 3,
  },
  FIRST_COMMENT: {
    id: "first_comment",
    name: "Commentator",
    description: "Left your first comment",
    icon: "💬",
    requirement: 1,
    type: "comment_count",
    tier: 1,
  },
  TEN_COMMENTS: {
    id: "ten_comments",
    name: "Chatterbox",
    description: "Left 10 comments",
    icon: "💬💬",
    requirement: 10,
    type: "comment_count",
    tier: 2,
  },
  HUNDRED_COMMENTS: {
    id: "hundred_comments",
    name: "Community Voice",
    description: "Left 100 comments",
    icon: "💬🔥",
    requirement: 100,
    type: "comment_count",
    tier: 3,
  },
  FIRST_STREAK: {
    id: "first_streak",
    name: "Consistency",
    description: "Maintained a 3-day streak",
    icon: "🔥",
    requirement: 3,
    type: "streak",
    tier: 1,
  },
  STREAK_MASTER: {
    id: "streak_master",
    name: "Streak Master",
    description: "Maintained a 7-day streak",
    icon: "🔥🔥",
    requirement: 7,
    type: "streak",
    tier: 2,
  },
  STREAK_LEGEND: {
    id: "streak_legend",
    name: "Streak Legend",
    description: "Maintained a 30-day streak",
    icon: "🔥🔥🔥",
    requirement: 30,
    type: "streak",
    tier: 3,
  },
  LIKER_1: {
    id: "liker_1",
    name: "First Liker",
    description: "Liked your first Pixel Art",
    icon: "👍",
    requirement: 1,
    type: "pixel_arts_liked",
    tier: 1,
  },
  LIKER_10: {
    id: "liker_10",
    name: "Thumbs Up",
    description: "Liked 10 Pixel Arts",
    icon: "👍👍",
    requirement: 10,
    type: "pixel_arts_liked",
    tier: 2,
  },
  LIKER_100: {
    id: "liker_100",
    name: "Big Fan",
    description: "Liked 100 Pixel Arts",
    icon: "💖",
    requirement: 100,
    type: "pixel_arts_liked",
    tier: 3,
  },
  LIKED_1: {
    id: "liked_1",
    name: "First Like",
    description: "Got your first like",
    icon: "⭐",
    requirement: 1,
    type: "likes_received",
    tier: 1,
  },
  LIKED_10: {
    id: "liked_10",
    name: "Popular",
    description: "Received 10 likes",
    icon: "🌟",
    requirement: 10,
    type: "likes_received",
    tier: 2,
  },
  LIKED_100: {
    id: "liked_100",
    name: "Superstar",
    description: "Received 100 likes",
    icon: "✨",
    requirement: 100,
    type: "likes_received",
    tier: 3,
  },
  REMIX_1: {
    id: "remix_1",
    name: "First Remix",
    description: "Remixed your first Pixel Art",
    icon: "🧩",
    requirement: 1,
    type: "remixes_made",
    tier: 1,
  },
  REMIX_10: {
    id: "remix_10",
    name: "Creative Remixer",
    description: "Remixed 10 Pixel Arts",
    icon: "🧠",
    requirement: 10,
    type: "remixes_made",
    tier: 2,
  },
  REMIX_100: {
    id: "remix_100",
    name: "Remix Master",
    description: "Remixed 100 Pixel Arts",
    icon: "🔁",
    requirement: 100,
    type: "remixes_made",
    tier: 3,
  },  
  REMIXED_1: {
    id: "remixed_1",
    name: "Inspired",
    description: "Someone remixed your Pixel Art",
    icon: "✨",
    requirement: 1,
    type: "remixes_received",
    tier: 1,
  },
  REMIXED_10: {
    id: "remixed_10",
    name: "Community Favorite",
    description: "Your Pixel Arts were remixed 10 times",
    icon: "🚀",
    requirement: 10,
    type: "remixes_received",
    tier: 2,
  },
  REMIXED_100: {
    id: "remixed_100",
    name: "Trendsetter",
    description: "Your Pixel Arts were remixed 100 times",
    icon: "🌈",
    requirement: 100,
    type: "remixes_received",
    tier: 3,
  },
  DAILY_PROMPT_1: {
    id: "daily_prompt_1",
    name: "Prompt Explorer",
    description: "Participated in your first daily prompt",
    icon: "📅",
    requirement: 1,
    type: "daily_prompt_participation",
    tier: 1,
  },
  DAILY_PROMPT_7: {
    id: "daily_prompt_7",
    name: "Prompt Regular",
    description: "Participated in 7 daily prompts",
    icon: "🗓️",
    requirement: 7,
    type: "daily_prompt_participation",
    tier: 2,
  },
  DAILY_PROMPT_30: {
    id: "daily_prompt_30",
    name: "Prompt Legend",
    description: "Participated in 30 daily prompts",
    icon: "🏅",
    requirement: 30,
    type: "daily_prompt_participation",
    tier: 3,
  },
  NIGHT_OWL: {
    id: "night_owl",
    name: "Night Owl",
    description: "Created Pixel Art after midnight",
    icon: "🌙",
    requirement: 1,
    type: "special",
    tier: 2,
  },
  EARLY_BIRD: {
    id: "early_bird",
    name: "Early Bird",
    description: "Created Pixel Art before 6 AM",
    icon: "🌅",
    requirement: 1,
    type: "special",
    tier: 2,
  },
};
